Hack fix of : error: bitwise operation between different enumeration types
* delete the following lines that cause build errors:

hardware/qcom-caf/msm8994/display/libcopybit/copybit_c2d.cpp:259:79: error: bitwise operation between different enumeration types ('C2D_RGB_FORMAT' and 'C2D_FORMAT_MODE') [-Werror,-Wenum-enum-conversion]
        case HAL_PIXEL_FORMAT_RGB_888:        return C2D_COLOR_FORMAT_888_RGB |
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~ ^
hardware/qcom-caf/msm8994/display/libcopybit/copybit_c2d.cpp:261:81: error: bitwise operation between different enumeration types ('C2D_RGB_FORMAT' and 'C2D_FORMAT_MODE') [-Werror,-Wenum-enum-conversion]
        case HAL_PIXEL_FORMAT_RGBX_8888:      return C2D_COLOR_FORMAT_8888_ARGB |
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
hardware/qcom-caf/msm8994/display/libcopybit/copybit_c2d.cpp:264:81: error: bitwise operation between different enumeration types ('C2D_RGB_FORMAT' and 'C2D_FORMAT_MODE') [-Werror,-Wenum-enum-conversion]
        case HAL_PIXEL_FORMAT_RGBA_8888:      return C2D_COLOR_FORMAT_8888_ARGB |
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
hardware/qcom-caf/msm8994/display/libcopybit/copybit_c2d.cpp:272:84: error: bitwise operation between different enumeration types ('C2D_YUV_FORMAT' and 'C2D_FORMAT_MODE') [-Werror,-Wenum-enum-conversion]
        case HAL_PIXEL_FORMAT_YCbCr_420_SP_TILED: return C2D_COLOR_FORMAT_420_NV12 |
                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~ ^
hardware/qcom-caf/msm8994/display/libcopybit/copybit_c2d.cpp:285:81: error: bitwise operation between different enumeration types ('C2D_RGB_FORMAT' and 'C2D_FORMAT_MODE') [-Werror,-Wenum-enum-conversion]
        case HAL_PIXEL_FORMAT_RGBX_8888:      return C2D_COLOR_FORMAT_8888_ARGB |
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^

Change-Id: I706ba915d4a3cd24702fd1adefd6796e898e46e2